- name: Start openmrs server
  systemd:
    name: openmrs
    state: started
  always_run: yes

- name: Start bahmni-reports service
  systemd:
    name: bahmni-reports
    state: started
  ignore_errors: true
  always_run: yes
