mysql_root_user: root
mysql_root_password: P@ssw0rd
copy_to_local_machine: no
backup_type: db
strategy: full
log_path: /var/log/backrest/
log_file: /var/log/backrest/mysql_backrest.log
bahmni_user: bahmni
bahmni_group: bahmni
openmrs:
  path: /db-backup/openmrs/
  retention_limit: 2
  restore_path: /db-backukp/openmrs/
bahmni_reports:
  path: /db-backup/reports/
  retention_limit: 2
  restore_path: /db-backukp/reports/
