download_folder: /opt
postgres_repo_rpm_name: pgdg-redhat-repo-42.0-23.noarch.rpm
postgres_repo_download_url: https://yum.postgresql.org/common/redhat/rhel-7-x86_64/pgdg-redhat-repo-42.0-23.noarch.rpm
postgres_repo_rpm_location: "{{download_folder}}/{{ postgres_repo_rpm_name}}"
openerp_db_username: odoo
openerp_db_password: openerp
odoo_master_password: Adm!n123