- name: Check if bahmni-web rpm needs an update
  command: yum list installed bahmni-web
  register: installed_bahmni_web
  ignore_errors: true

- name: Uninstall bahmni-web rpm
  package: name="bahmni-web" state=absent
  when: installed_bahmni_web.stdout.find("{{ bahmni_web_version }}") == -1

- name: Install bahmni-web from bahmni repo
  package: name="bahmni-web-{{ bahmni_web_version }}" state=present

- name: copy ssl conf file
  template:
      src=ssl.conf.j2
      dest=/etc/httpd/conf.d/ssl.conf
      mode=644
      owner={{ bahmni_user }}
      group={{ bahmni_group }}
  tags: event-log
