openmrs_user_id: admin
openmrs_user_password: test
bahmni_lab_port: 8052
openmrs_port: 8050
download_folder: /opt
postgres_repo_rpm_name: pgdg-redhat-repo-latest.noarch.rpm
postgres_repo_download_url: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/{{postgres_repo_rpm_name}}
postgres_repo_rpm_location: "{{download_folder}}/{{ postgres_repo_rpm_name}}"
bahmni_lab_server_opts: "-Xms512m -Xmx1024m"
bahmni_lab_debug_opts: "-agentlib:jdwp=transport=dt_socket,address=8001,server=y,suspend=n"
bahmni_lab_war_directory: "/var/run/bahmni-lab/bahmni-lab"
bahmni_lab_context_path: /openelis
bahmni_lab_base_dir: "/var/run/bahmni-lab"