- name: create full backup
  sudo: yes
  shell: cd /;sudo -u postgres pgbackrest --stanza=bahmni-postgres --type=full --log-level-console=info backup 2>>{{ logfile }}
  when: strategy == "full"

- name: create incremental backup
  sudo: yes
  shell: cd /;sudo -u postgres pgbackrest --stanza=bahmni-postgres --type=incr --log-level-console=info backup 2>>{{ logfile }}
  when: strategy == "incr"

- name: create bookeeping file
  sudo: yes
  script: bookeeping.sh {{ postgres.path }}

- name: Give permission to backup files
  shell: chmod -R 777 {{postgres.path}}
